- brand: Bershka
  merchant: Bershka
  source: scraper
  country: us
  debug: true
  respect_robots: false
  api:
    # Category endpoints - we use the category/product endpoint to get ALL product IDs first
    # Then fetch product details in batches using productsArray
    category_endpoints:
      - id: "1010834564"
        name: "men_all"
        gender: "MAN"
      - id: "1010193212"
        name: "women_jackets_trench"
        gender: "WOMAN"
      - id: "1010240019"
        name: "women_coats"
        gender: "WOMAN"
      - id: "1010276029"
        name: "women_jeans"
        gender: "WOMAN"
      - id: "1010193216"
        name: "women_pants"
        gender: "WOMAN"
      - id: "1010193213"
        name: "women_dresses_jumpsuit"
        gender: "WOMAN"
      - id: "1010193223"
        name: "women_sweaters_cardigans"
        gender: "WOMAN"
      - id: "1010193222"
        name: "women_sweatshirts_hoodies"
        gender: "WOMAN"
      - id: "1010193220"
        name: "women_tops_bodysuits"
        gender: "WOMAN"
      - id: "1010193217"
        name: "women_tshirts"
        gender: "WOMAN"
      - id: "1010193221"
        name: "women_shirts_blouses"
        gender: "WOMAN"
      - id: "1010280023"
        name: "women_skirts"
        gender: "WOMAN"
      - id: "1010194517"
        name: "women_shorts_jorts"
        gender: "WOMAN"
      - id: "1010429555"
        name: "women_matching_sets"
        gender: "WOMAN"
      - id: "1010361506"
        name: "women_swimwear"
        gender: "WOMAN"
      - id: "1010193192"
        name: "women_shoes"
        gender: "WOMAN"
        category: "footwear"
      - id: "1010193138"
        name: "women_bags"
        gender: "WOMAN"
        category: "accessory"
      - id: "1010193134"
        name: "women_accessories"
        gender: "WOMAN"
        category: "accessory"
    # URL templates - the KEY is using category_ids_url to get ALL product IDs first!
    # Step 1: Fetch ALL product IDs from this endpoint (returns 888+ IDs for men's category)
    category_ids_url: "https://www.bershka.com/itxrest/3/catalog/store/45009578/40259549/category/{category_id}/product?showProducts=false&showNoStock=false&appId=1&languageId=-15&locale=en_GB"
    # Step 2: Fetch product details in batches using those IDs
    products_url: "https://www.bershka.com/itxrest/3/catalog/store/45009578/40259549/productsArray?categoryId={category_id}&productIds={product_ids}&appId=1&languageId=-15&locale=en_GB"
    product_url_template: "https://www.bershka.com/us/{slug}-c0p{product_id}.html"
    # Batch size for product API calls (fetch 50 products at a time)
    batch_size: 50
    items_path: "products"
    field_map:
      external_id: "id"
      product_id: "id"
      title: ["nameEn", "name"]
      description: ["bundleProductSummaries[0].detail.longDescription", "bundleProductSummaries[0].detail.description"]
      price: "bundleProductSummaries[0].detail.colors[0].sizes[0].price"
      currency: "'EUR'"
      # Use deliveryUrl from xmedia which has the full image URL
      image_url: "bundleProductSummaries[0].detail.xmedia[0].xmediaItems[0].medias[0].extraInfo.deliveryUrl"
      brand: "'Bershka'"
      sizes: "bundleProductSummaries[0].detail.colors[0].sizes[].name"
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
      Accept: "application/json, text/plain, */*"
      Accept-Language: "en-GB,en;q=0.9"
      Referer: "https://www.bershka.com/"
    debug: true
    prewarm:
      - "https://www.bershka.com/us/"
